### ISSUE TITLE
batch destroy issues

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#1011]
```Failed to destroy the record /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/persistence.rb:750:in `_raise_record_not_destroyed' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/persistence.rb:357:in `destroy!' /opt/yeti-web/app/jobs/async_batch_destroy_job.rb:17:in `each' /opt/yeti-web/app/jobs/async_batch_destroy_job.rb:17:in `block in perform' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction' /usr/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/transactions.rb:212:in `transaction' /opt/yeti-web/app/jobs/async_batch_destroy_job.rb:16:in `perform' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.6/lib/active_job/execution.rb:39:in `block in perform_now' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:109:in `block in run_callbacks' /opt/yeti-web/lib/batch_jobs_log.rb:14:in `with_logic_log' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.10/lib/i18n.rb:314:in `with_locale' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.6/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `instance_exec' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.6/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `block in instrument' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/notifications/instrumenter.rb:23:in `instrument' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `instrument' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.6/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.6/lib/active_job/logging.rb:46:in `block in tag_logger' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `block in tagged' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:28:in `tagged' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `tagged' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.6/lib/active_job/logging.rb:46:in `tag_logger' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.6/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `instance_exec' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:136:in `run_callbacks' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.6/lib/active_job/execution.rb:38:in `perform_now' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.6/lib/active_job/execution.rb:24:in `block in execute' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:109:in `block in run_callbacks' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.6/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/execution_wrapper.rb:87:in `wrap' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/reloader.rb:73:in `block in wrap' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/execution_wrapper.rb:87:in `wrap' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/reloader.rb:72:in `wrap' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.6/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `instance_exec' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:136:in `run_callbacks' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.6/lib/active_job/execution.rb:22:in `execute' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.6/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:81:in `block in invoke_job' /opt/yeti-web/vendor/bundle/ruby/2.6.0/bundler/gems/prometheus_exporter-d8cd0abd6163/lib/prometheus_exporter/instrumentation/delayed_job.rb:35:in `call' /opt/yeti-web/vendor/bundle/ruby/2.6.0/bundler/gems/prometheus_exporter-d8cd0abd6163/lib/prometheus_exporter/instrumentation/delayed_job.rb:18:in `block (3 levels) in register_plugin' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block in add' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:78:in `invoke_job' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block (2 levels) in run' /usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout' /usr/lib/ruby/2.6.0/timeout.rb:103:in `timeout' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block in run' /usr/lib/ruby/2.6.0/benchmark.rb:308:in `realtime' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:229:in `run' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `reserve_and_run_one_job' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:213:in `block in work_off' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `times' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `work_off' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:175:in `block (4 levels) in start' /usr/lib/ruby/2.6.0/benchmark.rb:308:in `realtime' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:174:in `block (3 levels) in start' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:173:in `block (2 levels) in start' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `loop' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `block in start' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block in add' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:171:in `start' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/command.rb:137:in `run' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/command.rb:125:in `block in run_process' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/daemons-1.2.6/lib/daemons/application.rb:270:in `block in start_proc' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/daemons-1.2.6/lib/daemons/daemonize.rb:84:in `call_as_daemon' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/daemons-1.2.6/lib/daemons/application.rb:274:in `start_proc' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/daemons-1.2.6/lib/daemons/application.rb:300:in `start' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/daemons-1.2.6/lib/daemons/controller.rb:56:in `run' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/daemons-1.2.6/lib/daemons.rb:197:in `block in run_proc' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/daemons-1.2.6/lib/daemons/cmdline.rb:92:in `catch_exceptions' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/daemons-1.2.6/lib/daemons.rb:196:in `run_proc' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/command.rb:123:in `run_process' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/command.rb:104:in `block in daemonize' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/command.rb:102:in `times' /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.5/lib/delayed/command.rb:102:in `daemonize' /opt/yeti-web/bin/delayed_job:6:in `<top (required)>' /opt/yeti-web/vendor/bundler/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load' /opt/yeti-web/vendor/bundler/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load' /opt/yeti-web/vendor/bundler/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run' /opt/yeti-web/vendor/bundler/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec' /opt/yeti-web/vendor/bundler/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run' /opt/yeti-web/vendor/bundler/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command' /opt/yeti-web/vendor/bundler/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch' /opt/yeti-web/vendor/bundler/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch' /opt/yeti-web/vendor/bundler/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start' /opt/yeti-web/vendor/bundler/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start' /opt/yeti-web/vendor/bundler/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>' /opt/yeti-web/vendor/bundler/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors' /opt/yeti-web/vendor/bundler/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>' /opt/yeti-web/vendor/bundler/bin/bundle:23:in `load' /opt/yeti-web/vendor/bundler/bin/bundle:23:in `<main>'
```

**Comment by dmitry-sinina** [comment]
can't reproduce anymore
