### ISSUE TITLE
error when editing customer auth

### ISSUE THREAD

**Issue by hcaldicott** [yeti-switch/yeti-web#1493]
Hi team,

When editing customer auths, I receive the following error:

```
2024-06-25T21:49:16.678118+10:00 orch yeti-web[281893]: sentry
2024-06-25T21:49:16.680166+10:00 orch yeti-web[281893]: [d13efa6f-af93-4390-af85-6266058a46df] [d13efa6f-af93-4390-af85-6266058a46df] ActionView::Template::Error (undefined method `ransack' for #<Proc:0x00007faf7661b2c8 /opt/yeti-web/app/admin/routing/customers_auths.rb:300 (lambda)>):#012[d13efa6f-af93-4390-af85-6266058a46df]     1: # frozen_string_literal: true#012[d13efa6f-af93-4390-af85-6266058a46df]     2: insert_tag renderer_for(:edit)#012[d13efa6f-af93-4390-af85-6266058a46df]   #012[d13efa6f-af93-4390-af85-6266058a46df] lib/active_admin/views/active_admin_form.rb:20:in `association_ajax_input'#012[d13efa6f-af93-4390-af85-6266058a46df] app/admin/routing/customers_auths.rb:298:in `block (5 levels) in <main>'#012[d13efa6f-af93-4390-af85-6266058a46df] app/admin/routing/customers_auths.rb:259:in `block (4 levels) in <main>'#012[d13efa6f-af93-4390-af85-6266058a46df] app/admin/routing/customers_auths.rb:258:in `block (3 levels) in <main>'#012[d13efa6f-af93-4390-af85-6266058a46df] app/admin/routing/customers_auths.rb:257:in `block (2 levels) in <main>'#012[d13efa6f-af93-4390-af85-6266058a46df] config/initializers/instrumentation_notification.rb:15:in `process_action'
```

**Comment by dmitry-sinina** [comment]
it fixed in 1.12.163
