### ISSUE TITLE
yeti-web 1.4.8 fails to start when ldap.yml is present

### ISSUE THREAD

**Issue by cyril-s** [yeti-switch/yeti-web#197]
```
/home/yeti-web/app/models/admin_user.rb:64:in `alias_method': undefined method `valid_password?' for class `AdminUser (call 'AdminUser.connection' to establish a connection)' (NameError)
Did you mean?  validators
	from /home/yeti-web/app/models/admin_user.rb:64:in `<class:AdminUser>'
	from /home/yeti-web/app/models/admin_user.rb:27:in `<top (required)>'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:360:in `require_or_load'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:184:in `const_missing'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/inflector/methods.rb:261:in `const_get'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/inflector/methods.rb:261:in `block in constantize'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/inflector/methods.rb:259:in `each'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/inflector/methods.rb:259:in `inject'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:566:in `get'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:597:in `constantize'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/lib/devise.rb:291:in `get'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/lib/devise/mapping.rb:81:in `to'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/lib/devise/mapping.rb:76:in `modules'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/lib/devise/mapping.rb:93:in `routes'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/lib/devise/mapping.rb:160:in `default_used_route'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/lib/devise/mapping.rb:70:in `initialize'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/lib/devise.rb:325:in `new'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/lib/devise.rb:325:in `add_mapping'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/lib/devise/rails/routes.rb:238:in `block in devise_for'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/lib/devise/rails/routes.rb:237:in `each'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/lib/devise/rails/routes.rb:237:in `devise_for'
	from /home/yeti-web/config/routes.rb:2:in `block in <top (required)>'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:410:in `draw'
	from /home/yeti-web/config/routes.rb:1:in `<top (required)>'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application/routes_reloader.rb:40:in `each'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application.rb:170:in `reload_routes!'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/lib/devise/rails.rb:14:in `block in <class:Engine>'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application/finisher.rb:55:in `block in <module:Finisher>'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `run'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application.rb:352:in `initialize!'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `public_send'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `method_missing'
	from /home/yeti-web/config/environment.rb:5:in `<top (required)>'
	from config.ru:6:in `require'
	from config.ru:6:in `block in <main>'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/unicorn-4.8.3/lib/unicorn.rb:48:in `eval'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/unicorn-4.8.3/lib/unicorn.rb:48:in `block in builder'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:764:in `build_app!'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:137:in `start'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
	from /home/yeti-web/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `<main>'
```

Commenting out app/models/admin_user.rb:64 seems to fix the issue:
```ruby
    if ldap_config_exists?
      include AdminUserLdapHandler
    else
      include AdminUserDatabaseHandler
    end
  
    #alias_method :authenticate, :valid_password?
  
    def email
      @email ||= billing_contact.try!(:email)
    end
```

**Comment by Fivell** [comment]
was introduced here https://github.com/yeti-switch/yeti-web/pull/71
