### ISSUE TITLE
[new Rails] Realtime Data->Active calls broken

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#307]
```
May 13 01:03:01 yeti-demo YETI-admin[8869]: [01:03:01.288914 ] [ INFO]: Started GET "/active_calls?utf8=%E2%9C%93&q%5Bnode_id_eq%5D=8&commit=Filter" for 127.0.0.1 at 2018-05-13 01:03:01 +0300
May 13 01:03:01 yeti-demo YETI-admin[8869]: [01:03:01.290896 ] [ INFO]: Processing by ActiveCallsController#index as HTML
May 13 01:03:01 yeti-demo YETI-admin[8869]: [01:03:01.291399 ] [ INFO]: Parameters: {"utf8"=>"✓", "q"=>{"node_id_eq"=>"8"}, "commit"=>"Filter"}
May 13 01:03:01 yeti-demo YETI-admin[8869]: [01:03:01.486346 ] [ERROR]: undefined method `clean_search_params' for #<ActiveCallsController:0x0000000a541af0>#012Did you mean?  clear_cache_node_path
May 13 01:03:01 yeti-demo YETI-admin[8869]: [01:03:01.488239 ] [ WARN]: /home/yeti-web/app/admin/realtime_data/active_calls.rb:125:in `block (2 levels) in <top (required)>'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:413:in `instance_exec'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:413:in `block in make_lambda'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:178:in `block (2 levels) in halting_and_conditional'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:179:in `block in halting_and_conditional'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `block in invoke_before'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `each'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `invoke_before'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:130:in `run_callbacks'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/rescue.rb:20:in `proce
```

**Comment by dmitry-sinina** [comment]
outgoing registrations still broken:

```
May 13 15:54:36 yeti-demo YETI-admin[29859]: [15:54:36.703505 ] [ INFO]: Started GET "/outgoing_registrations" for 127.0.0.1 at 2018-05-13 15:54:36 +0300
May 13 15:54:36 yeti-demo YETI-admin[29859]: [15:54:36.704590 ] [ INFO]: Processing by OutgoingRegistrationsController#index as HTML
May 13 15:54:36 yeti-demo YETI-admin[29859]: [15:54:36.714687 ] [ERROR]: undefined method `delete_if' for nil:NilClass
May 13 15:54:36 yeti-demo YETI-admin[29859]: [15:54:36.715345 ] [ WARN]: /home/yeti-web/app/admin/realtime_data/outgoing_registrations.rb:27:in `find_collection'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activeadmin-1.0.0/lib/active_admin/resource_controller/data_access.rb:42:in `collection'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/inherited_resources-1.8.0/lib/inherited_resources/actions.rb:7:in `index'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activeadmin-1.0.0/lib/active_admin/resource_controller/streaming.rb:12:in `index'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/abstract_controller/base.rb:186:in `process_action'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/rendering.rb:30:in `process_action'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:131:in `run_callbacks'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/rescue.rb:20:in `process_action'#012/home/yeti-web/config/initializers/instrumentation_notification.rb:28:in `block in process_action'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'#012/home/yeti-web/vendor/bundle/rub
```
