### ISSUE TITLE
undefined method `model' for #<Billing::Invoice:0x0000000a8fe9e0>

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#355]
```Sep  1 11:23:36 yeti-demo YETI-admin[29071]: [11:23:36.557306 ] [ WARN]: undefined method `model' for #<Billing::Invoice:0x0000000a8fe9e0>
Sep  1 11:23:36 yeti-demo YETI-admin[29071]: [11:23:36.558014 ] [ WARN]: /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activemodel-5.1.6/lib/active_model/attribute_methods.rb:432:in `method_missing'#012/home/yeti-web/app/admin/billing/invoices.rb:41:in `create_resource'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/inherited_resources-1.8.0/lib/inherited_resources/actions.rb:33:in `create'#012/home/yeti-web/app/admin/billing/invoices.rb:47:in `create'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/abstract_controller/base.rb:186:in `process_action'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/rendering.rb:30:in `process_action'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:131:in `run_callbacks'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/rescue.rb:20:in `process_action'#012/home/yeti-web/config/initializers/instrumentation_notification.rb:28:in `block in process_action'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'#012/home/yeti-web/config/initializers/instrumentation_notification.rb:27:in `process_action'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/railties/controller_runtime.rb:22:in `process_action'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/abstract_controller/base.rb:124:in `process'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/rendering.rb:30:in `process'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal.rb:189:in `dispatch'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal.rb:253:in `dispatch'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:31:in `serve'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:50:in `block in serve'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:33:in `each'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:33:in `serve'#012/home/yeti-web/vendor/bundle/ruby/2.3.0```

**Comment by dmitry-sinina** [comment]
```
  controller do

    def create_resource(object)
      object.model.type_id=Billing::InvoiceType::MANUAL #TODO fix this. We need separate method for manual creation
      InvoiceGenerator.new(object.model).save!
    end

```
