### ISSUE TITLE
floating failing tests

### ISSUE THREAD

**Issue by senid231** [yeti-switch/yeti-web#493]
spec/acceptance/rest/admin/api/codec_groups_spec.rb:43

**Comment by senid231** [comment]
```
"Couldn't find Codec with 'id'=[1015]"

~activerecord-5.2.3/lib/active_record/relation/finder_methods.rb:346:in `raise_record_not_found_exception!'
~activerecord-5.2.3/lib/active_record/associations/collection_association.rb:69:in `ids_writer'
~activerecord-5.2.3/lib/active_record/associations/builder/collection_association.rb:65:in `codec_ids='
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/relationship_builder.rb:44:in `call'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/relationship_builder.rb:44:in `block in define_foreign_key_setter'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/resource.rb:307:in `_replace_to_many_links'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/resource.rb:82:in `block in replace_to_many_links'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/resource.rb:52:in `block in change'
~activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/resource.rb:51:in `change'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/resource.rb:81:in `replace_to_many_links'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/resource.rb:401:in `block in _replace_fields'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/resource.rb:400:in `each'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/resource.rb:400:in `_replace_fields'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/resource.rb:112:in `block in replace_fields'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/resource.rb:58:in `block (2 levels) in change'
~activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/resource.rb:57:in `block in change'
~activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/resource.rb:55:in `change'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/resource.rb:111:in `replace_fields'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/processor.rb:233:in `create_resource'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/processor.rb:58:in `block (2 levels) in process'
~activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/processor.rb:57:in `block in process'
~activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/processor.rb:56:in `process'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/operation.rb:16:in `process'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/operation_dispatcher.rb:58:in `block in process_operation'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/operation_dispatcher.rb:63:in `with_default_handling'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/operation_dispatcher.rb:57:in `process_operation'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/operation_dispatcher.rb:29:in `block (2 levels) in process'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/operation_dispatcher.rb:28:in `each'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/operation_dispatcher.rb:28:in `block in process'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/operation_dispatcher.rb:43:in `block in transaction'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/acts_as_resource_controller.rb:93:in `block (2 levels) in transaction'
~activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
~activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
~~monitor.rb:230:in `mon_synchronize'
~activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
~activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
~activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/acts_as_resource_controller.rb:92:in `block in transaction'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/operation_dispatcher.rb:42:in `transaction'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/operation_dispatcher.rb:24:in `process'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/acts_as_resource_controller.rb:86:in `block in process_operations'
~activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/acts_as_resource_controller.rb:85:in `process_operations'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/acts_as_resource_controller.rb:77:in `process_request'
~jsonapi-resources-0.9.1.beta1/lib/jsonapi/acts_as_resource_controller.rb:29:in `create'
~actionpack-5.2.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
~actionpack-5.2.3/lib/abstract_controller/base.rb:194:in `process_action'
~actionpack-5.2.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
~actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
~activesupport-5.2.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
app/controllers/api_controller.rb:13:in `db_logging'
~activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
~activesupport-5.2.3/lib/active_support/callbacks.rb:136:in `run_callbacks'
~actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
~actionpack-5.2.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
config/initializers/instrumentation_notification.rb:32:in `block in process_action'
~activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
~activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
~activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
config/initializers/instrumentation_notification.rb:31:in `process_action'
~actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
~activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
~actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'
~actionview-5.2.3/lib/action_view/rendering.rb:32:in `process'
~actionpack-5.2.3/lib/action_controller/metal.rb:191:in `dispatch'
~actionpack-5.2.3/lib/action_controller/metal.rb:252:in `dispatch'
~actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
~actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'
~actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'
~actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `each'
~actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve'
~actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
~warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
~warden-1.2.8/lib/warden/manager.rb:34:in `catch'
~warden-1.2.8/lib/warden/manager.rb:34:in `call'
~rack-2.0.6/lib/rack/tempfile_reaper.rb:15:in `call'
~rack-2.0.6/lib/rack/etag.rb:25:in `call'
~rack-2.0.6/lib/rack/conditional_get.rb:38:in `call'
~rack-2.0.6/lib/rack/head.rb:12:in `call'
~actionpack-5.2.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
~rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'
~rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'
~actionpack-5.2.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'
~actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
~activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
~actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
~actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
~actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
~railties-5.2.3/lib/rails/rack/logger.rb:38:in `call_app'
~railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'
~activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
~activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
~activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
~railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'
~actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
~request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
~actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
~rack-2.0.6/lib/rack/method_override.rb:22:in `call'
~rack-2.0.6/lib/rack/runtime.rb:22:in `call'
~activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
~actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
~actionpack-5.2.3/lib/action_dispatch/middleware/static.rb:127:in `call'
~rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
~railties-5.2.3/lib/rails/engine.rb:524:in `call'
~rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
~rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
~rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
~rack-test-1.1.0/lib/rack/test.rb:66:in `post'
~~forwardable.rb:230:in `post'
~rspec_api_documentation-5.0.0/lib/rspec_api_documentation/rack_test_client.rb:38:in `do_request'
~rspec_api_documentation-5.0.0/lib/rspec_api_documentation/client_base.rb:42:in `process'
~rspec_api_documentation-5.0.0/lib/rspec_api_documentation/client_base.rb:16:in `post'
~rspec_api_documentation-5.0.0/lib/rspec_api_documentation/dsl/endpoint.rb:61:in `do_request'
~rspec_api_documentation-5.0.0/lib/rspec_api_documentation/dsl/endpoint.rb:19:in `block in example_request'
~rspec-core-3.7.1/lib/rspec/core/example.rb:254:in `instance_exec'
~rspec-core-3.7.1/lib/rspec/core/example.rb:254:in `block in run'
~rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
~rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
~rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `block in run'
~rspec-core-3.7.1/lib/rspec/core/hooks.rb:606:in `block in run_around_example_hooks_for'
~rspec-core-3.7.1/lib/rspec/core/example.rb:342:in `call'
~rspec-rails-3.7.2/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
~rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
~rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
~rspec-core-3.7.1/lib/rspec/core/hooks.rb:375:in `execute_with'
~rspec-core-3.7.1/lib/rspec/core/hooks.rb:608:in `block (2 levels) in run_around_example_hooks_for'
~rspec-core-3.7.1/lib/rspec/core/example.rb:342:in `call'
~rspec-core-3.7.1/lib/rspec/core/hooks.rb:609:in `run_around_example_hooks_for'
~rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `run'
~rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
~rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
~rspec-core-3.7.1/lib/rspec/core/example.rb:251:in `run'
~rspec-core-3.7.1/lib/rspec/core/example_group.rb:628:in `block in run_examples'
~rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `map'
~rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `run_examples'
~rspec-core-3.7.1/lib/rspec/core/example_group.rb:590:in `run'
~rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `block in run'
~rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `map'
~rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `run'
~rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
~rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `map'
~rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
~rspec-core-3.7.1/lib/rspec/core/configuration.rb:1926:in `with_suite_hooks'
~rspec-core-3.7.1/lib/rspec/core/runner.rb:113:in `block in run_specs'
~rspec-core-3.7.1/lib/rspec/core/reporter.rb:79:in `report'
~rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
~rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
~rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
~rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
~rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
vendor/bundle/ruby/2.6.0/bin/rspec:23:in `load'
vendor/bundle/ruby/2.6.0/bin/rspec:23:in `<top (required)>'
~~~gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'
~~~gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
~~~gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
~~~gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
~~~gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
~~~gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
~~~gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
~~~gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
~~~gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
~~~gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
~~~gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
~~~gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
~~~gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
~~~bin/bundle:23:in `load'
~~~bin/bundle:23:in `<main>'
```

**Comment by senid231** [comment]
```
 expected #<Rateplan id: 12, name: "rateplan11_copy", profit_control_mode_id: 1, send_quality_alarms_to: [10, 9], uuid: "750cabba-d944-11e9-9367-0242ac110003"> to have attributes {:name => "rateplan11_copy", :profit_control_mode_id => 1, :send_quality_alarms_to => [9, 10]} but had attributes {:name => "rateplan11_copy", :profit_control_mode_id => 1, :send_quality_alarms_to => [10, 9]}
       Diff:
       @@ -1,4 +1,4 @@
        :name => "rateplan11_copy",
        :profit_control_mode_id => 1,
       -:send_quality_alarms_to => [9, 10],
       +:send_quality_alarms_to => [10, 9],
     Shared Example Group: :cloned_rateplan_is_valid called from ./spec/features/routing/rateplans/copy_rateplan_spec.rb:58
     # ./spec/features/routing/rateplans/copy_rateplan_spec.rb:14:in `block (3 levels) in <top (required)>'

rspec './spec/features/routing/rateplans/copy_rateplan_spec.rb[1:1:2:1]' # Copy Rateplan action success when "Send quality alarms to" has values creates new Rateplan with identical fields, except UUID
```

**Comment by senid231** [comment]
```
  1) Report Realtime Termination Distribution has one record
     Failure/Error: expect(page).to have_css('table.index_table tbody tr', count: 1)
       expected to find visible css "table.index_table tbody tr" 1 time, found 2 matches: "3 0 0.0 3 90 30 sec. 100.00% 100.00% 6.00", "contractor2695 | 8 5 0 0.0 5 150 30 sec. 100.00% 100.00% 10.00"
     # ./spec/features/realtime_data/report_realtime_termination_distribution/index_spec.rb:15:in `block (2 levels) in <top (required)>'

rspec ./spec/features/realtime_data/report_realtime_termination_distribution/index_spec.rb:14 # Report Realtime Termination Distribution has one record
```

**Comment by senid231** [comment]
```
1) Report Realtime Origination Performance has one record
     Failure/Error: expect(page).to have_css('table.index_table tbody tr', count: 1)
       expected to find visible css "table.index_table tbody tr" 1 time, found 2 matches: "customers_auth_167 | 1 0.0001 0.0003 2 min. 30 sec. 5 5 30 sec. 100.00%", "Not Authenticated 0.0002 0.0003 8 min. 0 sec. 16 16 30 sec. 100.00%"
     # ./spec/features/realtime_data/report_realtime_origination_performance/index_spec.rb:15:in `block (2 levels) in <top (required)>'

rspec ./spec/features/realtime_data/report_realtime_origination_performance/index_spec.rb:14 # Report Realtime Origination Performance has one record
```
