### ISSUE TITLE
Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)

### ISSUE THREAD

**Issue by Unnumbered** [yeti-switch/yeti-web#60]
I get this exception in development environment, when I try to open rails console.
ruby 2.3.3

trace
```
$ rails c
"Timezone Asia/Krasnoyarsk"
/home/andrey/web/yeti-web/lib/yeti/network_detector.rb:6: warning: already initialized constant Yeti::NetworkDetector::EMPTY_NETWORK_HINT
/home/andrey/web/yeti-web/lib/yeti/network_detector.rb:6: warning: previous definition of EMPTY_NETWORK_HINT was here
/home/andrey/.rvm/gems/ruby-2.3.3/gems/activesupport-4.1.9/lib/active_support/concern.rb:126:in `included': Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
        from /home/andrey/web/yeti-web/lib/yeti/network_detector.rb:8:in `<module:NetworkDetector>'
        from /home/andrey/web/yeti-web/lib/yeti/network_detector.rb:2:in `<module:Yeti>'
        from /home/andrey/web/yeti-web/lib/yeti/network_detector.rb:1:in `<top (required)>'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/andrey/web/yeti-web/config/initializers/yeti.rb:3:in `block in <top (required)>'
        from /home/andrey/web/yeti-web/config/initializers/yeti.rb:3:in `each'
        from /home/andrey/web/yeti-web/config/initializers/yeti.rb:3:in `<top (required)>'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `block in load'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/railties-4.1.9/lib/rails/engine.rb:648:in `block in load_config_initializer'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/activesupport-4.1.9/lib/active_support/notifications.rb:161:in `instrument'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/railties-4.1.9/lib/rails/engine.rb:647:in `load_config_initializer'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/railties-4.1.9/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/railties-4.1.9/lib/rails/engine.rb:611:in `each'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/railties-4.1.9/lib/rails/engine.rb:611:in `block in <class:Engine>'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `run'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/railties-4.1.9/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /home/andrey/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from /home/andrey/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/andrey/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        from /home/andrey/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/andrey/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/railties-4.1.9/lib/rails/initializable.rb:44:in `each'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/railties-4.1.9/lib/rails/initializable.rb:44:in `tsort_each_child'
        from /home/andrey/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:415:in `call'
        from /home/andrey/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
        from /home/andrey/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/andrey/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from /home/andrey/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from /home/andrey/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/andrey/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from /home/andrey/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/railties-4.1.9/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/railties-4.1.9/lib/rails/application.rb:300:in `initialize!'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `public_send'
        from /home/andrey/.rvm/gems/ruby-2.3.3/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `method_missing'
        from /home/andrey/web/yeti-web/config/environment.rb:5:in `<top (required)>'
...
```

**Comment by dmitry-sinina** [comment]
seems it is same issue as described in  #9

**Comment by dmitry-sinina** [comment]
Could you switch to branch issue_9 and check?

**Comment by dmitry-sinina** [comment]
fix was merged to master
