### ISSUE TITLE
Yeti-web startup error: undefined local variable or method `pop_id' for Routing::Simulation:Class

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#757]
```Jul 05 11:21:48 demo-yeti ruby[6704]: [6704] 2020-07-05 11:21:48 +0000: Puma starting in cluster mode...
Jul 05 11:21:48 demo-yeti ruby[6704]: [6704] 2020-07-05 11:21:48 +0000: * Version 4.3.5 (ruby 2.6.5-p114), codename: Mysterious Traveller
Jul 05 11:21:48 demo-yeti ruby[6704]: [6704] 2020-07-05 11:21:48 +0000: * Min threads: 2, max threads: 8
Jul 05 11:21:48 demo-yeti ruby[6704]: [6704] 2020-07-05 11:21:48 +0000: * Environment: production
Jul 05 11:21:48 demo-yeti ruby[6704]: [6704] 2020-07-05 11:21:48 +0000: * Process workers: 2
Jul 05 11:21:48 demo-yeti ruby[6704]: [6704] 2020-07-05 11:21:48 +0000: * Preloading application
Jul 05 11:21:49 demo-yeti ruby[6704]: App Timezone Etc/UTC
Jul 05 11:21:49 demo-yeti ruby[6704]: Yeti DB timezone UTC
Jul 05 11:21:49 demo-yeti ruby[6704]: CDR DB timezone UTC
Jul 05 11:21:49 demo-yeti ruby[6704]: ActiveRecord timezone utc
Jul 05 11:21:49 demo-yeti yeti-web[6704]: Raven 2.12.3 configured not to capture errors: No host specified, no public_key specified, no project_id specified
Jul 05 11:21:53 demo-yeti ruby[6704]: [6704] 2020-07-05 11:21:53 +0000: ! Unable to load application: NameError: undefined local variable or method `pop_id' for Routing::Simulation:Class
Jul 05 11:21:53 demo-yeti ruby[6704]: /opt/yeti-web/app/models/routing/simulation.rb:63:in `<class:Simulation>': undefined local variable or method `pop_id' for Routing::Simulation:Class (NameError)
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/app/models/routing/simulation.rb:3:in `<main>'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:378:in `block in require_or_load'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:13:in `loading'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:37:in `load_interlock'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:356:in `require_or_load'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:46:in `block in require_or_load'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:45:in `require_or_load'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:334:in `depend_on'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `depend_on'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:246:in `require_dependency'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:477:in `each'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:477:in `block in eager_load!'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:475:in `each'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:475:in `eager_load!'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:356:in `eager_load!'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/application/finisher.rb:69:in `each'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `instance_exec'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `run'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /usr/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /usr/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /usr/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /usr/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /usr/lib/ruby/2.6.0/tsort.rb:347:in `each'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /usr/lib/ruby/2.6.0/tsort.rb:347:in `call'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /usr/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /usr/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /usr/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:60:in `run_initializers'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/application.rb:361:in `initialize!'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/config/environment.rb:7:in `<top (required)>'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/config.ru:3:in `require'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/config.ru:3:in `block in <main>'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/rack-2.1.4/lib/rack/builder.rb:71:in `instance_eval'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/rack-2.1.4/lib/rack/builder.rb:71:in `initialize'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/config.ru:in `new'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/config.ru:in `<main>'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/rack-2.1.4/lib/rack/builder.rb:65:in `eval'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/rack-2.1.4/lib/rack/builder.rb:65:in `new_from_string'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/rack-2.1.4/lib/rack/builder.rb:59:in `load_file'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/rack-2.1.4/lib/rack/builder.rb:40:in `parse_file'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/configuration.rb:321:in `load_rackup'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/configuration.rb:246:in `app'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/runner.rb:155:in `load_and_bind'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/cluster.rb:413:in `run'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:172:in `run'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/cli.rb:80:in `run'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/bin/puma:10:in `<top (required)>'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
Jul 05 11:21:53 demo-yeti ruby[6704]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<main>'
```

looks like bug was introduced in commit https://github.com/yeti-switch/yeti-web/commit/2daf51692c06ee1b928c5c905d52d1b1db35583c

**Comment by dmitry-sinina** [comment]
other issue:
```Jul 05 11:26:09 demo-yeti yeti-web[7025]: Raven 2.12.3 configured not to capture errors: No host specified, no public_key specified, no project_id specified
Jul 05 11:26:12 demo-yeti ruby[7025]: [7025] 2020-07-05 11:26:12 +0000: ! Unable to load application: ArgumentError: Unknown validator: 'GreaterThanOrEqualToValidator'
Jul 05 11:26:12 demo-yeti ruby[7025]: /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.3/lib/active_model/validations/validates.rb:121:in `rescue in block in validates': Unknown validator: 'GreaterThanOrEqualToValidator' (ArgumentError)
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.3/lib/active_model/validations/validates.rb:118:in `block in validates'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.3/lib/active_model/validations/validates.rb:114:in `each'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.3/lib/active_model/validations/validates.rb:114:in `validates'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/app/models/routing/simulation.rb:63:in `<class:Simulation>'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/app/models/routing/simulation.rb:3:in `<main>'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:378:in `block in require_or_load'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:13:in `loading'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:37:in `load_interlock'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:356:in `require_or_load'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:46:in `block in require_or_load'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:45:in `require_or_load'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:334:in `depend_on'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `depend_on'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:246:in `require_dependency'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:477:in `each'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:477:in `block in eager_load!'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:475:in `each'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:475:in `eager_load!'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:356:in `eager_load!'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/application/finisher.rb:69:in `each'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `instance_exec'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `run'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /usr/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /usr/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /usr/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /usr/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /usr/lib/ruby/2.6.0/tsort.rb:347:in `each'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /usr/lib/ruby/2.6.0/tsort.rb:347:in `call'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /usr/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /usr/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /usr/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:60:in `run_initializers'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/application.rb:361:in `initialize!'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/config/environment.rb:7:in `<top (required)>'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/config.ru:3:in `require'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/config.ru:3:in `block in <main>'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/rack-2.1.4/lib/rack/builder.rb:71:in `instance_eval'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/rack-2.1.4/lib/rack/builder.rb:71:in `initialize'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/config.ru:in `new'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/config.ru:in `<main>'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/rack-2.1.4/lib/rack/builder.rb:65:in `eval'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/rack-2.1.4/lib/rack/builder.rb:65:in `new_from_string'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/rack-2.1.4/lib/rack/builder.rb:59:in `load_file'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/rack-2.1.4/lib/rack/builder.rb:40:in `parse_file'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/configuration.rb:321:in `load_rackup'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/configuration.rb:246:in `app'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/runner.rb:155:in `load_and_bind'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/cluster.rb:413:in `run'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:172:in `run'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/cli.rb:80:in `run'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/bin/puma:10:in `<top (required)>'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
Jul 05 11:26:12 demo-yeti ruby[7025]:         from /opt/yeti-web/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<main>'
```
