### ISSUE TITLE
fix floating failed tests

### ISSUE THREAD

**Issue by senid231** [yeti-switch/yeti-web#846]
```
1) BatchUpdateForm::Dialpeer check validation when all fields filled with valid values should pass validation
     Failure/Error: option_name = page.find(:xpath, ".//option[@value = '#{value}']").text
     
     Capybara::ElementNotFound:
       Unable to find xpath ".//option[@value = '1']" within #<Capybara::Node::Element tag="select" path="//HTML[1]/BODY[1]/DIV[8]/FORM[1]/DIV[1]/UL[1]/LI[6]/SELECT[1]">
     # ./spec/support/helpers/feature_test_helper.rb:8:in `block in select_by_value'
     # ./spec/support/helpers/feature_test_helper.rb:7:in `select_by_value'
     # ./spec/features/routing/dialpeers/batch_update_spec.rb:92:in `block (2 levels) in <top (required)>'
     # ./spec/features/routing/dialpeers/batch_update_spec.rb:227:in `block (2 levels) in <top (required)>'
     # ./spec/features/routing/dialpeers/batch_update_spec.rb:244:in `block (5 levels) in <top (required)>'
     # ./spec/features/routing/dialpeers/batch_update_spec.rb:243:in `block (4 levels) in <top (required)>'

rspec ./spec/features/routing/dialpeers/batch_update_spec.rb:242
```

**Comment by Skumring** [comment]
```
Failures:

  1) Copy Rateplan action success when "Send quality alarms to" has values creates new Rateplan with identical fields, except UUID
     Failure/Error:
       create(:rateplan,
              send_quality_alarms_to: send_to_ids).reload # after_save

     ActiveRecord::RecordInvalid:
       Validation failed: Send quality alarms to is invalid
     Shared Example Group: :cloned_rateplan_is_valid called from ./spec/features/routing/rateplans/copy_rateplan_spec.rb:56
     # ./spec/features/routing/rateplans/copy_rateplan_spec.rb:26:in `block (3 levels) in <top (required)>'

  2) Dialpeers PUT /api/rest/admin/dialpeers/:id update values
     Failure/Error: contact.update!(email: email) if @email

     ActiveRecord::NotNullViolation:
       PG::NotNullViolation: ERROR:  null value in column "item_type" of relation "versions" violates not-null constraint
       DETAIL:  Failing row contains (287, null, null, null, null, null, null, null, null, 79565).
       : INSERT INTO "versions" DEFAULT VALUES RETURNING "id"
     # ./app/models/admin_user.rb:49:in `block in <class:AdminUser>'
     # ------------------
     # --- Caused by: ---
     # PG::NotNullViolation:
     #   ERROR:  null value in column "item_type" of relation "versions" violates not-null constraint
     #   DETAIL:  Failing row contains (287, null, null, null, null, null, null, null, null, 79565).
     #   ./app/models/admin_user.rb:49:in `block in <class:AdminUser>'

**Comment by Skumring** [comment]
```
  1) Create new Gateway with termination shows flash notice
     Failure/Error: visit new_gateway_path

     Ferrum::StatusError:
       Request to http://127.0.0.1:9887/gateways/new reached server, but there are still pending connections: http://127.0.0.1:9887/gateways/new
     Shared Example Group: :shows_flash_message called from ./spec/features/equipment/gateways/new_gateway_spec.rb:57
     # ./spec/features/equipment/gateways/new_gateway_spec.rb:29:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Ferrum::TimeoutError:
     #   Timed out waiting for response. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the :timeout option to a higher value might help.
     #   ./spec/features/equipment/gateways/new_gateway_spec.rb:29:in `block (2 levels) in <top (required)>'

**Comment by dmitry-sinina** [comment]
> ```
>   1) Create new Gateway with termination shows flash notice
>      Failure/Error: visit new_gateway_path
> 
>      Ferrum::StatusError:
>        Request to http://127.0.0.1:9887/gateways/new reached server, but there are still pending connections: http://127.0.0.1:9887/gateways/new
>      Shared Example Group: :shows_flash_message called from ./spec/features/equipment/gateways/new_gateway_spec.rb:57
>      # ./spec/features/equipment/gateways/new_gateway_spec.rb:29:in `block (2 levels) in <top (required)>'
>      # ------------------
>      # --- Caused by: ---
>      # Ferrum::TimeoutError:
>      #   Timed out waiting for response. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the :timeout option to a higher value might help.
>      #   ./spec/features/equipment/gateways/new_gateway_spec.rb:29:in `block (2 levels) in <top (required)>'
> ```

There is rspec log for this case -  https://github.com/yeti-switch/yeti-web/runs/1785666203?check_suite_focus=true
also we have screenshot in artefacts:

![image](https://user-images.githubusercontent.com/12762053/106202110-1e031400-61c2-11eb-90ea-809e4979fe48.png)

**Comment by paratskiy** [comment]
```
Failures:

  1) Index Billing contacts visit all contacts
     Failure/Error: visit billing_contacts_path

     Ferrum::StatusError:
       Request to http://127.0.0.1:9887/billing_contacts reached server, but there are still pending connections: http://127.0.0.1:9887/billing_contacts
     # ./spec/features/billing/contacts/index_contacts_spec.rb:9:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Ferrum::TimeoutError:
     #   Timed out waiting for response. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the :timeout option to a higher value might help.
     #   ./spec/features/billing/contacts/index_contacts_spec.rb:9:in `block (2 levels) in <top (required)>'
```

**Comment by paratskiy** [comment]
```
Failures:

  1) Api::Rest::Customer::V1::CdrsController GET index should eq 2
     Failure/Error: it { expect(response_data.size).to eq(cdrs.size) }

       expected: 2
            got: 3

       (compared using ==)
     # ./spec/controllers/api/rest/customer/cdrs_controller_spec.rb:20:in `block (3 levels) in <top (required)>'
```
