### ISSUE TITLE
ActionView::Template::Error app/admin/reports/customer_traffic_data_by_vendors.rb in block (3 levels) in <main>

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#889]
```
NoMethodError: undefined method `delete' for :red:Symbol
  from active_admin/views/components/status_tag.rb:32:in `build'
  from arbre/element/builder_methods.rb:30:in `block in build_tag'
  from arbre/context.rb:92:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:26:in `build_tag'
  from arbre/element/builder_methods.rb:39:in `insert_tag'
  from arbre/element/builder_methods.rb:14:in `status_tag'
  from app/admin/reports/customer_traffic_data_by_vendors.rb:60:in `block (3 levels) in <main>'
  from lib/active_admin/views/components/table_for.rb:140:in `render_data'
  from lib/active_admin/views/components/table_for.rb:134:in `block in build_table_cell'
  from arbre/element/builder_methods.rb:31:in `block in build_tag'
  from arbre/context.rb:92:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:26:in `build_tag'
  from arbre/element/builder_methods.rb:39:in `insert_tag'
  from arbre/element/builder_methods.rb:14:in `td'
  from lib/active_admin/views/components/table_for.rb:133:in `build_table_cell'
  from lib/active_admin/views/components/table_for.rb:59:in `block (2 levels) in column'
  from arbre/context.rb:92:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  from lib/active_admin/views/components/table_for.rb:58:in `block in column'
  from draper/delegation.rb:10:in `each'
  from draper/delegation.rb:10:in `each_with_index'
  from draper/delegation.rb:10:in `each_with_index'
  from lib/active_admin/views/components/table_for.rb:57:in `column'
  from arbre/element.rb:177:in `method_missing'
  from lib/active_admin/views/index_as_table.rb:38:in `column'
  from app/admin/reports/customer_traffic_data_by_vendors.rb:52:in `block (2 levels) in <main>'
  from lib/active_admin/views/index_as_table.rb:62:in `instance_exec'
  from lib/active_admin/views/index_as_table.rb:62:in `block in build'
  from arbre/element.rb:33:in `build'
  from arbre/html/tag.rb:19:in `build'
  from lib/active_admin/views/components/table_for.rb:30:in `build'
  from arbre/element/builder_methods.rb:28:in `block in build_tag'
  from arbre/context.rb:92:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:26:in `build_tag'
  from arbre/element/builder_methods.rb:39:in `insert_tag'
  from lib/active_admin/views/index_as_table.rb:21:in `table_for'
  from lib/active_admin/views/index_as_table.rb:60:in `build'
  from arbre/element/builder_methods.rb:30:in `block in build_tag'
  from arbre/context.rb:92:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:26:in `build_tag'
  from arbre/element/builder_methods.rb:39:in `insert_tag'
  from active_admin/views/pages/index.rb:140:in `block (2 levels) in render_index'
  from arbre/element/builder_methods.rb:31:in `block in build_tag'
  from arbre/context.rb:92:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:26:in `build_tag'
  from arbre/element/builder_methods.rb:39:in `insert_tag'
  from arbre/element/builder_methods.rb:14:in `div'
  from active_admin/views/pages/index.rb:139:in `block in render_index'
  from arbre/element/builder_methods.rb:31:in `block in build_tag'
  from arbre/context.rb:92:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:26:in `build_tag'
  from arbre/element/builder_methods.rb:39:in `insert_tag'
  from arbre/element/builder_methods.rb:14:in `paginated_collection'
  from active_admin/views/pages/index.rb:133:in `render_index'
  from active_admin/views/pages/index.rb:50:in `build_collection'
  from active_admin/views/pages/index.rb:28:in `block in main_content'
  from active_admin/views/pages/index.rb:38:in `wrap_with_batch_action_form'
  from active_admin/views/pages/index.rb:26:in `main_content'
  from active_admin/views/pages/base.rb:101:in `block (2 levels) in build_main_content_wrapper'
  from arbre/element/builder_methods.rb:31:in `block in build_tag'
  from arbre/context.rb:92:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:26:in `build_tag'
  from arbre/element/builder_methods.rb:39:in `insert_tag'
  from arbre/element/builder_methods.rb:14:in `div'
  from active_admin/views/pages/base.rb:100:in `block in build_main_content_wrapper'
  from arbre/element/builder_methods.rb:31:in `block in build_tag'
  from arbre/context.rb:92:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:26:in `build_tag'
  from arbre/element/builder_methods.rb:39:in `insert_tag'
  from arbre/element/builder_methods.rb:14:in `div'
  from active_admin/views/pages/base.rb:99:in `build_main_content_wrapper'
  from active_admin_sidebar/activeadmin_views_pages_base.rb:7:in `block in build_page_content'
  from arbre/element/builder_methods.rb:31:in `block in build_tag'
  from arbre/context.rb:92:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:26:in `build_tag'
  from arbre/element/builder_methods.rb:39:in `insert_tag'
  from arbre/element/builder_methods.rb:14:in `div'
  from active_admin_sidebar/activeadmin_views_pages_base.rb:5:in `build_page_content'
  from active_admin/views/pages/base.rb:59:in `block (2 levels) in build_page'
  from arbre/element/builder_methods.rb:31:in `block in build_tag'
  from arbre/context.rb:92:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:26:in `build_tag'
  from arbre/element/builder_methods.rb:39:in `insert_tag'
  from arbre/element/builder_methods.rb:14:in `div'
  from active_admin/views/pages/base.rb:55:in `block in build_page'
  from arbre/context.rb:92:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  from active_admin/views/pages/base.rb:54:in `build_page'
  from active_admin/views/pages/base.rb:9:in `build'
  from arbre/element/builder_methods.rb:30:in `block in build_tag'
  from arbre/context.rb:92:in `with_current_arbre_element'
  from arbre/element/builder_methods.rb:26:in `build_tag'
  from arbre/element/builder_methods.rb:39:in `insert_tag'
  from bundle/ruby/2.6.0/gems/activeadmin-2.7.0/app/views/active_admin/resource/index.html.arb:2:in `block in _vendor_bundle_ruby_______gems_activeadmin_______app_views_active_admin_resource_index_html_arb___2181707843861424490_47251210482780'
  from arbre/context.rb:45:in `instance_eval'
  from arbre/context.rb:45:in `initialize'
  from bundle/ruby/2.6.0/gems/activeadmin-2.7.0/app/views/active_admin/resource/index.html.arb:1:in `new'
  from bundle/ruby/2.6.0/gems/activeadmin-2.7.0/app/views/active_admin/resource/index.html.arb:1:in `_vendor_bundle_ruby_______gems_activeadmin_______app_views_active_admin_resource_index_html_arb___2181707843861424490_47251210482780'
  from action_view/template.rb:159:in `block in render'
  from active_support/notifications.rb:170:in `instrument'
  from action_view/template.rb:354:in `instrument_render_template'
  from action_view/template.rb:157:in `render'
  from action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  from action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
  from active_support/notifications.rb:168:in `block in instrument'
  from active_support/notifications/instrumenter.rb:23:in `instrument'
  from active_support/notifications.rb:168:in `instrument'
  from action_view/renderer/abstract_renderer.rb:43:in `instrument'
  from action_view/renderer/template_renderer.rb:53:in `block in render_template'
  from action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  from action_view/renderer/template_renderer.rb:52:in `render_template'
  from action_view/renderer/template_renderer.rb:16:in `render'
  from action_view/renderer/renderer.rb:44:in `render_template'
  from action_view/renderer/renderer.rb:25:in `render'
  from action_view/rendering.rb:103:in `_render_template'
  from action_controller/metal/streaming.rb:219:in `_render_template'
  from action_view/rendering.rb:84:in `render_to_body'
  from action_controller/metal/rendering.rb:52:in `render_to_body'
  from action_controller/metal/renderers.rb:142:in `render_to_body'
  from abstract_controller/rendering.rb:25:in `render'
  from action_controller/metal/rendering.rb:36:in `render'
  from action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
  from active_support/core_ext/benchmark.rb:14:in `block in ms'
  from benchmark.rb:308:in `realtime'
  from active_support/core_ext/benchmark.rb:14:in `ms'
  from action_controller/metal/instrumentation.rb:46:in `block in render'
  from action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  from active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
  from action_controller/metal/instrumentation.rb:45:in `render'
  from action_controller/responder.rb:238:in `default_render'
  from action_controller/responder.rb:170:in `to_html'
  from responders/flash_responder.rb:107:in `to_html'
  from action_controller/responder.rb:163:in `respond'
  from action_controller/responder.rb:156:in `call'
  from action_controller/respond_with.rb:211:in `respond_with'
  from inherited_resources/actions.rb:7:in `index'
  from active_admin/resource_controller/streaming.rb:12:in `index'
  from action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  from abstract_controller/base.rb:194:in `process_action'
  from action_controller/metal/rendering.rb:30:in `process_action'
  from abstract_controller/callbacks.rb:42:in `block in process_action'
  from active_support/callbacks.rb:132:in `run_callbacks'
  from abstract_controller/callbacks.rb:41:in `process_action'
  from action_controller/metal/rescue.rb:22:in `process_action'
  from config/initializers/instrumentation_notification.rb:32:in `block in process_action'
  from active_support/notifications.rb:168:in `block in instrument'
  from active_support/notifications/instrumenter.rb:23:in `instrument'
  from active_support/notifications.rb:168:in `instrument'
  from config/initializers/instrumentation_notification.rb:31:in `process_action'
  from action_controller/metal/params_wrapper.rb:256:in `process_action'
  from active_record/railties/controller_runtime.rb:24:in `process_action'
  from abstract_controller/base.rb:134:in `process'
  from action_view/rendering.rb:32:in `process'
  from action_controller/metal.rb:191:in `dispatch'
  from action_controller/metal.rb:252:in `dispatch'
  from action_dispatch/routing/route_set.rb:52:in `dispatch'
  from action_dispatch/routing/route_set.rb:34:in `serve'
  from action_dispatch/journey/router.rb:52:in `block in serve'
  from action_dispatch/journey/router.rb:35:in `each'
  from action_dispatch/journey/router.rb:35:in `serve'
  from action_dispatch/routing/route_set.rb:840:in `call'
  from warden/manager.rb:36:in `block in call'
  from warden/manager.rb:34:in `catch'
  from warden/manager.rb:34:in `call'
  from rack/tempfile_reaper.rb:17:in `call'
  from rack/etag.rb:27:in `call'
  from rack/conditional_get.rb:27:in `call'
  from rack/head.rb:14:in `call'
  from action_dispatch/http/content_security_policy.rb:18:in `call'
  from rack/session/abstract/id.rb:269:in `context'
  from rack/session/abstract/id.rb:263:in `call'
  from action_dispatch/middleware/cookies.rb:670:in `call'
  from action_dispatch/middleware/callbacks.rb:28:in `block in call'
  from active_support/callbacks.rb:98:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:26:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:61:in `call'
  from action_dispatch/middleware/show_exceptions.rb:33:in `call'
  from rails/rack/logger.rb:38:in `call_app'
  from rails/rack/logger.rb:26:in `block in call'
  from active_support/tagged_logging.rb:71:in `block in tagged'
  from active_support/tagged_logging.rb:28:in `tagged'
  from active_support/tagged_logging.rb:71:in `tagged'
  from rails/rack/logger.rb:26:in `call'
  from action_dispatch/middleware/remote_ip.rb:81:in `call'
  from request_store/middleware.rb:19:in `call'
  from action_dispatch/middleware/request_id.rb:27:in `call'
  from rack/method_override.rb:24:in `call'
  from rack/runtime.rb:24:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from action_dispatch/middleware/executor.rb:14:in `call'
  from rack/sendfile.rb:113:in `call'
  from rails/engine.rb:524:in `call'
  from puma/configuration.rb:228:in `call'
  from puma/server.rb:713:in `handle_request'
  from puma/server.rb:472:in `process_client'
  from puma/server.rb:328:in `block in run'
  from puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by Fivell** [comment]
`status_tag('Rejected', :red)` need to be replaced with     `status_tag('Rejected',  class: 'red')`
