### ISSUE TITLE
application does not start with "development" environment

### ISSUE THREAD

**Issue by furmur** [yeti-switch/yeti-web#9]
```
$ RAILS_ENV=development bundle exec rails s
=> Booting Thin
=> Rails 4.1.9 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
Exiting
/home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/concern.rb:126:in `included': Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
        from /home/laeda/projects/yeti-web/lib/yeti/registration_reloader.rb:4:in `<module:RegistrationReloader>'
        from /home/laeda/projects/yeti-web/lib/yeti/registration_reloader.rb:2:in `<module:Yeti>'
        from /home/laeda/projects/yeti-web/lib/yeti/registration_reloader.rb:1:in `<top (required)>'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/laeda/projects/yeti-web/config/initializers/yeti.rb:3:in `block in <top (required)>'
        from /home/laeda/projects/yeti-web/config/initializers/yeti.rb:3:in `each'
        from /home/laeda/projects/yeti-web/config/initializers/yeti.rb:3:in `<top (required)>'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `block in load'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/engine.rb:648:in `block in load_config_initializer'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/notifications.rb:161:in `instrument'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/engine.rb:647:in `load_config_initializer'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/engine.rb:611:in `each'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/engine.rb:611:in `block in <class:Engine>'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `run'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        from /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/initializable.rb:44:in `each'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/initializable.rb:44:in `tsort_each_child'
        from /usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
        from /usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/application.rb:300:in `initialize!'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `public_send'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `method_missing'
        from /home/laeda/projects/yeti-web/config/environment.rb:5:in `<top (required)>'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/laeda/projects/yeti-web/config.ru:5:in `block in <main>'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
        from /home/laeda/projects/yeti-web/config.ru:in `new'
        from /home/laeda/projects/yeti-web/config.ru:in `<main>'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:49:in `eval'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:49:in `new_from_string'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:40:in `parse_file'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/rack-1.5.5/lib/rack/server.rb:277:in `build_app_and_options_from_config'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/rack-1.5.5/lib/rack/server.rb:199:in `app'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/commands/server.rb:50:in `app'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/rack-1.5.5/lib/rack/server.rb:314:in `wrapped_app'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/commands/server.rb:130:in `log_to_stdout'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/commands/server.rb:67:in `start'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:81:in `block in server'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:76:in `tap'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:76:in `server'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /home/laeda/projects/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by furmur** [comment]
seems fixed in branch `issue_9`
