### ISSUE TITLE
Destinations routing_for_contains filter exception

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#937]
```
yeti-web[22062]: [fd17530d-39a0-4924-a92e-54e7eece0476] Started GET "/destinations?utf8=%E2%9C%93&q%5Brouting_for_contains%5D=3801111111111&commit=Filter&order=id_desc" for 2a01:ad00:2:5::223 at 2021-04-09 07:33:00 +0000
yeti-web[22062]: [fd17530d-39a0-4924-a92e-54e7eece0476] Processing by DestinationsController#index as HTML
yeti-web[22062]: [fd17530d-39a0-4924-a92e-54e7eece0476] Parameters: {"utf8"=>"✓", "q"=>{"routing_for_contains"=>"380978377478"}, "commit"=>"Filter", "order"=>"id_desc"}
yeti-web[22062]: [fd17530d-39a0-4924-a92e-54e7eece0476] Rendering vendor/bundle/ruby/2.6.0/gems/activeadmin-2.7.0/app/views/active_admin/resource/index.html.arb
yeti-web[22062]: [fd17530d-39a0-4924-a92e-54e7eece0476] Rendered vendor/bundle/ruby/2.6.0/gems/activeadmin-2.7.0/app/views/active_admin/resource/index.html.arb (256.5ms)
yeti-web[22062]: [fd17530d-39a0-4924-a92e-54e7eece0476] Completed 500 Internal Server Error in 412ms
yeti-web[22062]: [fd17530d-39a0-4924-a92e-54e7eece0476] 
yeti-web[22062]: [fd17530d-39a0-4924-a92e-54e7eece0476] ActionView::Template::Error (PG::UndefinedColumn: ERROR:  column t_dst.rateplan_id does not exist#012LINE 5:         rank() OVER (PARTITION BY t_dst.rateplan_id ORDER BY...#012                                          ^#012: SELECT COUNT(*) FROM "class4"."destinations" WHERE (destinations.id in (#012      select id from#012      (#012        SELECT t_dst.id as id,#012        rank() OVER (PARTITION BY t_dst.rateplan_id ORDER BY length(t_dst.prefix) desc) as r#012        FROM class4.destinations t_dst#012        WHERE prefix_range(t_dst.prefix)@>prefix_range('380978377478') and#012          length('3801111111111')>=t_dst.dst_number_min_length and#012          length('3801111111111')<=t_dst.dst_number_max_length#012      ) h where h.r=1#012    ))):
yeti-web[22062]: [fd17530d-39a0-4924-a92e-54e7eece0476] 1: insert_tag renderer_for(:index)
yeti-web[22062]: [fd17530d-39a0-4924-a92e-54e7eece0476] 
yeti-web[22062]: [fd17530d-39a0-4924-a92e-54e7eece0476] config/initializers/instrumentation_notification.rb:32:in `block in process_action'#012[fd17530d-39a0-4924-a92e-54e7eece0476] config/initializers/instrumentation_notification.rb:31:in `process_action'
```

capybara test for filter should be added

**Comment by dmitry-sinina** [comment]
``` 
scope :routing_for_contains, lambda { |prx|
    where('destinations.id in (
      select id from
      (
        SELECT t_dst.id as id,
        rank() OVER (PARTITION BY t_dst.rate_group_id ORDER BY length(t_dst.prefix) desc) as r
        FROM class4.destinations t_dst
        WHERE prefix_range(t_dst.prefix)@>prefix_range(?) and
          length(?)>=t_dst.dst_number_min_length and
          length(?)<=t_dst.dst_number_max_length
      ) h where h.r=1
    )', prx, prx, prx)
  }
```
